"""
Automated Unit Tests for EduGenie Modular Architecture
"""

import unittest
import json
from backend.parsers import clean_json_output, generate_export_document, extract_delimited_section, extract_text_from_upload
from backend.gemini_client import handle_gemini_error, resolve_api_key, get_gemini_model


class TestEduGenieBackend(unittest.TestCase):

    def test_clean_json_output_with_markdown_fences(self):
        """Test that JSON markdown code blocks are properly stripped."""
        raw_llm_output = """```json
[
  {
    "id": 1,
    "question": "What is 2+2?",
    "options": ["3", "4", "5", "6"],
    "correct_answer": "4",
    "explanation": "Basic addition."
  }
]
```"""
        cleaned = clean_json_output(raw_llm_output)
        parsed = json.loads(cleaned)
        self.assertIsInstance(parsed, list)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0]["correct_answer"], "4")

    def test_clean_json_output_plain(self):
        """Test clean_json_output handles raw JSON without backticks."""
        raw_json = '[{"front": "Term", "back": "Definition"}]'
        cleaned = clean_json_output(raw_json)
        parsed = json.loads(cleaned)
        self.assertEqual(parsed[0]["front"], "Term")

    def test_handle_gemini_error_rate_limit(self):
        """Test that 429 quota exceptions map to user-friendly messages."""
        mock_exception = Exception("429 ResourceExhausted: Quota exceeded for model gemini-1.5-pro")
        message = handle_gemini_error(mock_exception)
        self.assertIn("Rate Limit Exceeded", message)
        self.assertIn("gemini-1.5-flash", message)

    def test_handle_gemini_error_auth_failure(self):
        """Test that 403 API key exceptions map to actionable advice."""
        mock_exception = Exception("403 API_KEY_INVALID: API key not valid.")
        message = handle_gemini_error(mock_exception)
        self.assertIn("Invalid API Key", message)
        self.assertIn("Google AI Studio", message)

    def test_extract_delimited_section(self):
        """Test structured delimiter extraction."""
        sample_doc = """[SECTION: Core Intuition]
This is the core concept.
[SECTION: Deep Breakdown]
Here is the mechanism."""
        intuition = extract_delimited_section(sample_doc, "Core Intuition")
        breakdown = extract_delimited_section(sample_doc, "Deep Breakdown")
        self.assertEqual(intuition, "This is the core concept.")
        self.assertEqual(breakdown, "Here is the mechanism.")

    def test_generate_export_document_html(self):
        """Test HTML document generation utility."""
        title = "Calculus Revision"
        content = "Derivatives represent instantaneous rate of change."
        html_output = generate_export_document(title, content, doc_format="html")
        self.assertIn("<title>Calculus Revision | EduGenie Study Material</title>", html_output)
        self.assertIn("Derivatives represent instantaneous rate of change.", html_output)
        self.assertIn("Generated by EduGenie AI", html_output)

    def test_generate_export_document_txt(self):
        """Test plain text document export utility."""
        title = "Physics"
        content = "# Newton's Law\nF = ma"
        txt_output = generate_export_document(title, content, doc_format="txt")
        self.assertIn("PHYSICS", txt_output)
        self.assertIn("Newton's Law", txt_output)

    def test_extract_text_from_upload_none(self):
        """Test extract_text_from_upload returns None gracefully when given None."""
        self.assertIsNone(extract_text_from_upload(None))

    def test_services_import_and_callable(self):
        """Test all backend service endpoints are cleanly exported and callable."""
        from backend.services import generate_explanation, generate_quiz, generate_flashcards, generate_summary, chat_doubt_solver, generate_learning_plan
        self.assertTrue(callable(generate_explanation))
        self.assertTrue(callable(generate_quiz))
        self.assertTrue(callable(generate_flashcards))
        self.assertTrue(callable(generate_summary))
        self.assertTrue(callable(chat_doubt_solver))
        self.assertTrue(callable(generate_learning_plan))

    def test_auth_system(self):
        """Test user authentication and registration workflows."""
        from backend.auth import authenticate_user, register_user
        
        # Test demo user login
        auth_ok, user_data, msg = authenticate_user("student@edugenie.ai", "edugenie123")
        self.assertTrue(auth_ok)
        self.assertEqual(user_data["name"], "Demo Scholar")

        # Test invalid password
        bad_auth, _, _ = authenticate_user("student@edugenie.ai", "wrongpwd")
        self.assertFalse(bad_auth)


if __name__ == "__main__":
    unittest.main()
