"""
Parsers, file extractors, and formatting utilities for EduGenie.
"""

import io
import re
from typing import Optional, Any
from PIL import Image
from pypdf import PdfReader


def clean_json_output(raw_text: str) -> str:
    """Cleans markdown JSON code blocks from LLM output."""
    if not raw_text:
        return ""
    raw_text = raw_text.strip()
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", raw_text)
    if match:
        return match.group(1).strip()
    return raw_text


def extract_text_from_pdf(file_bytes: bytes) -> str:
    """Extracts text content from uploaded PDF bytes."""
    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        extracted_text = []
        for page in reader.pages:
            t = page.extract_text()
            if t:
                extracted_text.append(t)
        return "\n".join(extracted_text)
    except Exception as e:
        return f"Error extracting PDF text: {str(e)}"


def extract_text_from_upload(uploaded_file: Any) -> Optional[str]:
    """
    Unified extractor for Streamlit UploadedFile objects (PDF, TXT, Markdown).
    Eliminates redundant file-handling code across views.
    """
    if uploaded_file is None:
        return None
    try:
        file_bytes = uploaded_file.getvalue()
        file_type = getattr(uploaded_file, "type", "") or ""
        file_name = getattr(uploaded_file, "name", "").lower()
        
        if "pdf" in file_type or file_name.endswith(".pdf"):
            return extract_text_from_pdf(file_bytes)
        else:
            return file_bytes.decode("utf-8", errors="ignore")
    except Exception as e:
        return f"Error reading uploaded file: {str(e)}"


def process_image(file_bytes: bytes) -> Optional[Image.Image]:
    """Processes uploaded image bytes into a PIL Image."""
    try:
        return Image.open(io.BytesIO(file_bytes))
    except Exception:
        return None


def extract_delimited_section(text: str, section_name: str) -> Optional[str]:
    """Extracts a section from structured text formatted with [SECTION: Name]."""
    if not text:
        return None
    pattern = rf"\[SECTION:\s*{section_name}\]([\s\S]*?)(?=\[SECTION:|$)"
    match = re.search(pattern, text, re.IGNORECASE)
    return match.group(1).strip() if match else None


def generate_export_document(title: str, markdown_content: str, doc_format: str = "html") -> str:
    """Generates formatted document content for export (.html, .txt, .md)."""
    if doc_format == "html":
        # Format HTML with modern typography & clean presentation
        escaped_content = markdown_content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br>")
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | EduGenie Study Material</title>
    <style>
        :root {{
            --primary: #4f46e5;
            --accent: #06b6d4;
            --text-dark: #0f172a;
            --bg-light: #f8fafc;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.7;
            color: var(--text-dark);
            background: var(--bg-light);
            max-width: 860px;
            margin: 40px auto;
            padding: 0 24px;
        }}
        .header-card {{
            background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%);
            color: white;
            padding: 28px;
            border-radius: 14px;
            margin-bottom: 28px;
            box-shadow: 0 10px 25px -5px rgba(79, 70, 229, 0.3);
        }}
        .header-card h1 {{ margin: 0 0 8px 0; font-size: 2rem; color: #ffffff; }}
        .badge {{ background: rgba(255, 255, 255, 0.2); color: white; padding: 4px 12px; border-radius: 20px; font-size: 0.85em; font-weight: 600; display: inline-block; }}
        .content-card {{
            background: white;
            border-radius: 12px;
            padding: 32px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
            border: 1px solid #e2e8f0;
            font-size: 1.02rem;
        }}
        pre, code {{ background: #f1f5f9; padding: 3px 8px; border-radius: 6px; font-family: "JetBrains Mono", Consolas, monospace; font-size: 0.9em; }}
        footer {{ text-align: center; margin-top: 30px; font-size: 0.85rem; color: #64748b; }}
    </style>
</head>
<body>
    <div class="header-card">
        <h1>{title}</h1>
        <span class="badge">🎓 Generated by EduGenie AI Study Assistant</span>
    </div>
    <div class="content-card">
        {escaped_content}
    </div>
    <footer>
        <p>Created with EduGenie • Empowering Autonomous Academic Learning</p>
    </footer>
</body>
</html>"""
    elif doc_format == "txt":
        clean_text = re.sub(r"[#*_`]", "", markdown_content)
        return f"=========================================\n  {title.upper()}\n  EduGenie AI Study Material\n=========================================\n\n{clean_text}\n\nGenerated by EduGenie AI."
    return markdown_content
